trigger: 
  - develop
pool:
  vmImage: 'windows-latest'
steps:
  - task: NuGetToolInstaller@0

  - task: NuGetRestore@1
    inputs:
      restoreSolution: '**/*.sln'

  - task: VSBuild@1
    inputs:
      solution: '**/*.sln'
      msbuildArgs: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(buildartifactstagingdirectory)'
      ArtifactName: 'drop'
      publishLocation: 'container'    